version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_DEV_PASSWORD}
    ports:
      - "33333:3306"
    container_name: mysql_db
    volumes:
      - db-data:/var/lib/mysql
    tty: true
    stdin_open: true
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  node_api:
    build:
      dockerfile: Dockerfile.dev
      context: ./node_api
    volumes:
      - /app/node_modules
      - ./node_api:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 5000:5000
volumes:
  db-data:
    driver: local
